sudo: false
language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js: 
  - 8
before_install:
  - npm i -g npm
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run semantic-release